name = "gypsum-test"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-04"

[[r2_buckets]]
binding = 'GYPSUM_BUCKET'
bucket_name = 'gypsum-test'
preview_bucket_name = 'gypsum-test'

